splitted output files and tables containing sensitive/non sensitive information
ldsec/medco-loader pull request #23
Opened 2020-07-21 10:02 UTC by f-marino

2020-07-21 10:18 UTC, JoaoAndreSa commented
Ok so here is couple of changes to do:
1. `"SENSITIVE_TAGGED_NON_SENSITIVE"` this one should not exist (you can delete it)
2. `"NEW_PATIENT_NUM_NON_SENSITIVE"` same it does not exist for the non_sensitive
3. `"NEW_ENCOUNTER_NUM_NON_SENSITIVE"` same
4.  for these files that you deleted you can keep the sensitive version without the SENSITIVE tag
      e.g. SENSITIVE_TAGGED_SENSITIVE => SENSITIVE_TAGGED
5. `GenerateLoadingDataScript`for this one maybe it's better to generate two functions because some stuff we don't need to add in the non-sensitive: e.g. 
`loading += `\copy ` + OutputFilePaths["SENSITIVE_TAGGED_NON_SENSITIVE"].TableName + ` FROM '` + OutputFilePaths["SENSITIVE_TAGGED_NON_SENSITIVE"].Path + `' ESCAPE '"' DELIMITER ',' CSV HEADER;` + "\n"`

2020-07-21 10:49 UTC, JoaoAndreSa commented
Other things to do:
1. We need to change the root path (so the files are written in two different folders)

2020-07-21 10:59 UTC, f-marino commented
> Other things to do:
> 
> 1. We need to change the root path (so the files are written in two different folders)

What do you mean here? At the moment sensitive and non sensitive files are written under the sensitive and non-sensitive folders...isn't that enough?

2020-07-21 11:00 UTC, JoaoAndreSa commented
@f-marino nothing

2020-07-21 11:01 UTC, JoaoAndreSa commented
@f-marino sorry my mistake. I wanted to deleted that comment but i closed the PR

2020-07-21 11:01 UTC, f-marino commented
ahahah no problem

2020-07-21 11:12 UTC, f-marino commented
> 5. `GenerateLoadingDataScript`for this one maybe it's better to generate two functions because some stuff we don't need to add in the non-sensitive: e.g.
>    `loading += `\copy `+ OutputFilePaths["SENSITIVE_TAGGED_NON_SENSITIVE"].TableName +` FROM '`+ OutputFilePaths["SENSITIVE_TAGGED_NON_SENSITIVE"].Path +`' ESCAPE '"' DELIMITER ',' CSV HEADER;` + "\n"`

Mmmh @JoaoAndreSa you mean that non-sensitive tables may need to be treated differently than sensitive tables in the way we load data into them? Or just that some tables do not have a non-sensitive version? In the second case I would simply delete the loading instructions for the non-sensitive tables that do not exist.

2020-07-21 11:25 UTC, JoaoAndreSa commented
> > 1. `GenerateLoadingDataScript`for this one maybe it's better to generate two functions because some stuff we don't need to add in the non-sensitive: e.g.
> >    `loading += `\copy `+ OutputFilePaths["SENSITIVE_TAGGED_NON_SENSITIVE"].TableName +` FROM '`+ OutputFilePaths["SENSITIVE_TAGGED_NON_SENSITIVE"].Path +`' ESCAPE '"' DELIMITER ',' CSV HEADER;` + "\n"`
> 
> Mmmh @JoaoAndreSa you mean that non-sensitive tables may need to be treated differently than sensitive tables in the way we load data into them? Or just that some tables do not have a non-sensitive version? In the second case I would simply delete the loading instructions for the non-sensitive tables that do not exist.

For this particular example it's only that some tables do not have a non-sensitive version. But later on we will write different stuff for similar files depending on whether it's sensitive or not. For this examples it only improves readability. It won't change much having everything in one function or two functions :)

2020-07-21 11:49 UTC, JoaoAndreSa commented
After this is done you should try changing the table access (`ConvertTableAcess()`) to write in the two different files you previously created. The contents of both are the same so this should be an easy change and you can probably test by running the `_test` to see if it works :)

2020-07-21 11:56 UTC, f-marino commented
@JoaoAndreSa I should have addressed your previous comments, start working on the access table

2020-07-21 12:20 UTC, f-marino commented
@JoaoAndreSa what is the strategy we are going to follow for the ConvertXXX functions? Two functions, one for the sensitive and one for the non-sensitive data, ore one functions managing both cases?

2020-07-21 12:23 UTC, JoaoAndreSa commented
Let's keep one for now (we might need stuff from both converts). If later we see that we can clearly (and without replicating code) split them we do it.

2020-07-21 13:46 UTC, f-marino commented
The ConvertTableAccess test passes, just I noticed that I have to create manually the directory tree (e.g. data/i2b2/converted/non_sensitive)  for the test to pass. Is this normal? Don't we want the functions to automatically create the directories when needed?

2020-07-21 14:07 UTC, JoaoAndreSa commented
Don't remember, but maybe it is. I know there is an option in the os.Create() to enable this. You can definitely add it :) 

That's good news. So now we move in the `ConvertLocalOntology`. This one should be also simple. If you look inside the function there is a `ConvertClearLocalTable()` and a `ConvertSensitiveLocalTable()`. So what happens is that all the _local_birn.csv_, _local_i2b2.csv_ generated by the `ConvertClearLocalTable()` are part of the **non-sensitive** DB and the sensitive_tagged.csv is part of the **sensitive** DB. This means you only need to do 2 things:
1. Apparently i was unaware, but we don't need the local_*.csv files for the sensitive DB so we can remove their creation
2. Ensure that the local_*.csv and sensitive_tagged.csv are stored in the correct folder (non-sensitive, sensitive respectively)

2020-07-22 09:21 UTC, f-marino commented
- Now the directory tree is automatically created
- Removed the useless local sensitive files
- The files are saved in the correct folder
- I tried to run the ConvertOntology test but it didn't work

1 : websocket.go:186 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2001
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2020-07-22 11:14:01 on address local://127.0.0.1:2010
2 : websocket.go:186 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2011
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2020-07-22 11:14:01 on address local://127.0.0.1:2020
2 : websocket.go:186 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2021
2 : loaderI2B2.go:1035 (i2b2.EncryptAndTag)  - Finished encrypting the sensitive data... [11] ( 8.142343ms )
2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: tagging_loading_phase
E : websocket.go:887 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
F : loaderI2B2.go:1049 (i2b2.EncryptAndTag)  - Error during DDT: sending: connection read: websocket: close 1002 (protocol error): unexpected error: panic: runtime error: invalid memory address or nil pointer dereference

Process finished with exit code 1

2020-07-22 14:09 UTC, JoaoAndreSa commented
Sorry for the delay @f-marino I was focused on another project :) Can you pin point where the nil pointer is, to help me understand what could possibly be? It should be somewhere inside here `client.SendSurveyDDTRequestTerms()`. 

After this the next couple of files is the MedCo Ontology: `GenerateMedCoOntology(). This one again we have to split the files. One remains as is (the non-sensitive) the other will contain all sensitive concepts. These are easily recognisable because they have this metadata added to them. E.g.

``` 
"<?xml version=""1.0""?><ValueMetadata><Version>MedCo-0.1</Version><EncryptedType>CONCEPT_INTERNAL_NODE</EncryptedType><NodeEncryptID>0</NodeEncryptID><ChildrenEncryptIDs>"1;10;7;8;9;2;3;4;5;6"
```

In the code it's easy to spot this difference:

``` golang
for _, so := range TablesMedCoOntology[rawName].Clear {
	csvOutputFile.WriteString(so.ToCSVText() + "\n")
}
``` 

``` golang
for _, so := range TablesMedCoOntology[rawName].Sensitive {
	csvOutputFile.WriteString(so.ToCSVText() + "\n")
}
```

2020-07-23 08:30 UTC, f-marino commented
@JoaoAndreSa the error is returned when you call `c.SendProtobuf(c.entryPoint, &sdq, &resp)`, line 54 of services/api

2020-07-23 08:55 UTC, f-marino commented
Done (still the same problem with the test)

2020-07-23 14:18 UTC, JoaoAndreSa commented
Ok for the bug then I have to check it in person ;) 
Moving to the `ConvertPatientDimension()` and `ConvertVisitDimension()`.

For the  `ConvertPatientDimension()` we need to be careful to just add the dummies to the sensitive file

```golang
// add dummies
for dummyNum, patientNum := range TableDummyToPatient {
	MapNewPatientNum[dummyNum] = strconv.FormatInt(int64(perm[i]), 10)

	patient := TablePatientDimension[PatientDimensionPK{PatientNum: patientNum}]
	patient.PK.PatientNum = strconv.FormatInt(int64(perm[i]), 10)
	ef := libunlynx.EncryptInt(pk, 0)
	patient.EncryptedFlag = *ef

	csvOutputFile.WriteString(patient.ToCSVText(empty) + "\n")
	i++
}
```

I think we also need to add a new column to the sensitive, but I'm not sure exactly (we need to talk with mickael and Juan for this).

For this one `ConvertVisitDimension()` for what I understand (something to ask tomorrow let's hope I don't forget) is that the **non-sensitive** as the regular visits (no dummies) and the **sensitive** is empty. Just comment the dummy part for now until we are certain what exactly they want to do with this particular table for the **sensitive** DB.

2020-07-24 11:11 UTC, f-marino commented
As far as I understood everything below `//add dummies` in the function must not be run when we are dealing with non sensitive data, while the function should remain exactly the same when we are dealing with sensitive data, right?

what about the `// re-randomize the patient_num` section? Should it be run for non sensitive data too?

2020-07-24 12:49 UTC, JoaoAndreSa commented
I think we need to re-randomize the non-sensitive patient IDs. But I'm not sure, I will ask in this meeting. However there has to exists a way to link the patients between databases by having the same randomized IDs between DBs (protected somehow not to reveal the dummy ones). 

So my idea would be to re-randomize the patients IDs and then use these new IDs for both the sensitive and non-sensitive tables but let's make sure it's like that.

2020-07-27 10:24 UTC, JoaoAndreSa commented
So just a quick review of what we discussed Friday:
1. _Visit Dimension_ we only keep the non-sensitive one; 
2. _Patient Dimension_ we keep as is the non-sensitive (only randomize the ids). We randomize again for the sensitive DB and add the dummies.
3. We keep all data for the non-sensitive DB we don't delete the unnecessary fields (we only do this for the sensitive DB)

2020-07-30 16:08 UTC, JoaoAndreSa commented
So first briefing of today's meeting:
- No more meeting tomorrow is cancelled;
- We are not dropping the changes to the loader for now we continue with them, in the future we might have to add an extra piece of parsing (of the modifiers) :/;

```
1. I think all functions have been modified, except ConvertConceptDimension() , please tell me what to with it
2. The tests of the modified function pass, except the TestConvertOntology , we have to look into this
3. What I have to do with the patient_dimension and the dummy_to_patient files generated by the python script? Do we need them? If not, do I need to pass the patient_dimension file to the script?
4. I didn’t know yet how long does it take the dummy generation with a reduced number of concepts as I could not run the ConvertAll  test. Let’s focus on the modification on the ConvertCopnceptDimension() and on the TestConvertOntology first.
```

1. First question the comments kind of answer it:
```golang
// if the concept is non-sensitive -> keep it as it is
if _, ok := TableLocalOntologyClear[cd.PK.ConceptPath]; ok {
      csvOutputFile.WriteString(cd.ToCSVText() + "\n")
// if the concept is sensitive -> fetch its encrypted tag and tag_id
} else if _, ok := MapConceptPathToTag[cd.PK.ConceptPath]; ok {
```

If it's not sensitive keep as is, otherwise delete all unnecessary fields and add the TAG_ID and the encrypted_tag.

2. We should meet to check live what is the problem (we could meet at 15h to replace the original meeting :)) 

3. We need the dummy_to_patient files for sure this is what we use to add the dummies. Where are you exactly calling the python scripts?

4. Ok for me :)

P.S. I was talking with Mickael about the planing and I got us two more weeks to try and finish this splitting part. When are your holidays planned?

2020-08-03 12:05 UTC, f-marino commented
Everything should be now modified to work with the new workflow (still to be tested yet). Please tell me if you see some evident logical mistake. The ConvertOntology and ConvertConceptDimension tests fail with same error on the unlynx side:

`2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: tagging_loading_phase
E : websocket.go:887 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
F : loaderI2B2.go:1091 (i2b2.EncryptAndTag)  - Error during DDT: sending: connection read: websocket: close 1002 (protocol error): unexpected error: panic: runtime error: invalid memory address or nil pointer dereference`

when you have time we can look into it

2020-08-03 14:37 UTC, f-marino commented
Also, I started modifying medco-deployment to reflect the changes that we made here so that we can test everything, but I have a few doubts. Here, for example: https://github.com/ldsec/medco-deployment/blob/master/docker-images/i2b2/sql/65-medco-ontology.sh

Is table_access exactly the same for medco_ont_sensitive and medco_ont_non_sensitive? I just have to skip all the sensitive_tagged stuff for the non_sensitive (creation of the sensitive_tagged table, insertion of the sensitive_tagged table in the table_access, etc), right?

What about the medco_ont.schemes table? How does it look like for the sensitive and non sensitive?

2020-08-04 08:55 UTC, JoaoAndreSa commented
> Also, I started modifying medco-deployment to reflect the changes that we made here so that we can test everything, but I have a few doubts. Here, for example: https://github.com/ldsec/medco-deployment/blob/master/docker-images/i2b2/sql/65-medco-ontology.sh
> 
> Is table_access exactly the same for medco_ont_sensitive and medco_ont_non_sensitive? I just have to skip all the sensitive_tagged stuff for the non_sensitive (creation of the sensitive_tagged table, insertion of the sensitive_tagged table in the table_access, etc), right?
> 
> What about the medco_ont.schemes table? How does it look like for the sensitive and non sensitive?

I can take a look but the deployment part I did not do it. @mickmis maybe you can give some help here. :/

2020-08-04 08:56 UTC, JoaoAndreSa commented
> Also, I started modifying medco-deployment to reflect the changes that we made here so that we can test everything, but I have a few doubts. Here, for example: https://github.com/ldsec/medco-deployment/blob/master/docker-images/i2b2/sql/65-medco-ontology.sh
> 
> Is table_access exactly the same for medco_ont_sensitive and medco_ont_non_sensitive? I just have to skip all the sensitive_tagged stuff for the non_sensitive (creation of the sensitive_tagged table, insertion of the sensitive_tagged table in the table_access, etc), right?
> 
> What about the medco_ont.schemes table? How does it look like for the sensitive and non sensitive?

I will try to locally execute these to see if I have the same problem.

2020-08-04 09:21 UTC, JoaoAndreSa commented
I quickly check and it runs for me those function (at least in my computer). I need to see it live to figure out what could be happening.

2020-08-04 10:02 UTC, JoaoAndreSa commented
ok i'm taking a closer look at the code, here are some first comments:
1. I think that if one of the medco_xxx.csv for the sensitive is empty i think we should not consider or do we still build the table. @mickmis what is your thought on this?
2. `Patient_Dimension` we should add a new column for the new entry (for GECO). You can check the M3 interface document it should be listed there. @mickmis how is this planed to work. Do we create this column directly on the .csv or we just add the value like we do with the encrypted_dummy_flag?
3. For some reason it did not generate the observation_fact (trying to figure out why)
4. more to come...

2020-08-12 11:50 UTC, JoaoAndreSa commented
Ok so now comes the modifier part. The modifiers are represented by a `modifier_cd` in the `FactTable` column (concepts are represented with `concept_cd`). 

As an example, the Principal Diagnosis modifier is linked to this concept `\i2b2\Diagnoses\Musculoskeletal and connective tissue (710-739)\` and its children (if i'm not mistaken is what the % represents, you should check in the documentation I sent you):

`"1","\Principal Diagnosis\","Principal Diagnosis","N","RA ","\N","1","\N","MODIFIER_CD","MODIFIER_DIMENSION","MODIFIER_PATH","T","LIKE","\Principal Diagnosis\","\N","Principal Diagnosis","\i2b2\Diagnoses\Musculoskeletal and connective tissue (710-739)\%","2011-04-14 12:55:00","\N","\N","\N","\N","\N","\N","\N"`

Spread throughout the code you will some `if !modifiers` and that is where we will need to change the code:

```golang
if strings.ToLower(so.FactTableColumn) != "modifier_cd" {
	so.NodeEncryptID = IDConcepts
```

For the non-sensitive it should be easy (I think!!), you simply have to copy them as is to the converted file. Probably even just removing the if in _line 902_ could be enough, but you need to test. 
For the sensitive is more tricky. For me the easiest way is to begin by traversing the local ontology files (`i2b2.csv`, `birn.csv`, etc.) and convert the modifiers to concepts and then proceed with the normal loading. Picking the example above:

`"1","\Principal Diagnosis\","Principal Diagnosis","N","RA ","\N","1","\N","MODIFIER_CD","MODIFIER_DIMENSION","MODIFIER_PATH","T","LIKE","\Principal Diagnosis\","\N","Principal Diagnosis","\i2b2\Diagnoses\Musculoskeletal and connective tissue (710-739)\%","2011-04-14 12:55:00","\N","\N","\N","\N","\N","\N","\N"`

and the actual concept,

`"2","\i2b2\Diagnoses\Musculoskeletal and connective tissue (710-739)\","Musculoskeletal and connective tissue","N","FA ","\N","\N","\N","concept_cd","concept_dimension","concept_path","T","LIKE","\i2b2\Diagnoses\Musculoskeletal and connective tissue (710-739)\","\N","Diagnoses \ Musculoskeletal and connective tissue","@","2006-04-17 00:00:00","2006-04-17 00:00:00","2006-04-17 00:00:00","RPDR","\N","\N","\N","\N"`

we would replace the modifier entry by this:

`"3","\i2b2\Diagnoses\Musculoskeletal and connective tissue (710-739)\Principal Diagnosis\","Principal Diagnosis","N","FA ","\N","\N","\N","concept_cd","concept_dimension","concept_path","T","LIKE","\i2b2\Diagnoses\Musculoskeletal and connective tissue (710-739)\Principal Diagnosis\","\N","Diagnoses \ Musculoskeletal and connective tissue","@","2006-04-17 00:00:00","2006-04-17 00:00:00","2006-04-17 00:00:00","RPDR","\N","\N","\N","\N"`.

I will ask in the group, but again I think we need to do this with all the children concepts (the `%` symbol).

This is completely new so I'm not sure it will work or not. You should probably take a look at what each column represents and see if there are no obvious 'complications'.  For example, in the converted example there is this `"Diagnoses \ Musculoskeletal and connective tissue"` that I don't exactly know how it should become... maybe something like `"Diagnoses \ Musculoskeletal and connective tissue \ Principal Diagnosis"`, but I'm not sure. Maybe it's not even important.

I also think that we should keep this modular, therefore add a flag or a global variable to control whether or not we enable the modifiers. 

[OPTIONAL]
P.S. We need to fix the lint errors to make Travis pass I think (you can try `make local` to see them). If you want you can leave this until the end, right before we merge to `master`.

2020-09-18 08:04 UTC, JoaoAndreSa requested changes
@f-marino from a quick overview it looks good (i liked your refactoring in multiple files :D). The only thing I spotted was that in some test files you changed the package. I usually put all the tests in different packages to make a clear separation between the two, but maybe there is a reason why you did it like that. [here](https://medium.com/@matryer/5-simple-tips-and-tricks-for-writing-unit-tests-in-golang-619653f90742)

After this is resolved I think most probably we should not merge to the `dev branch`. Either we keep this branch as is or we create/rename a `dev-v4` and place this code there. It's completely undefined when we will make use of this code so let's just keep in a separate branch.

2020-09-18 08:27 UTC, f-marino commented on loader/i2b2/loaderI2B2_test.go
> +	assert.Nil(t, parseTableAccess())
yes, exactly. So, all the comments are related to the test packaging so I will address them here.
In my opinion having the tests outside the package of the functions forced you to export each and every function and variable in an unnatural way, as most of them just belongs to the package and should not be exposed outside. As you can see now the only exported function of the loaderi2b2 package is, indeed, LoadI2B2Data, which I think is cleaner. Probably the tests for this function should go in a different package, but for the moment we don't have any because it involves also the loading in the database, and we did not go that far yet :D anyway, to be consistent with the article you linked I could change the loaderI2B2_test.go file to the loaderI2B2_internal_test.go (same thing for the structs_test.go). Shall we go this way?

2020-10-14 10:09 UTC, mickmis commented
Moved to ldsec/medco#59.

2020-10-14 10:09 UTC, closed without merging